version: "3"

services:
  #frontend build
  frontend:
    build: .
    image: ${DOCKER_REPOSITORY}:latest
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    container_name: dailyfix-frontend
    restart: always
    ports:
      - 3000:3000


